wget https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/inject/dapi-volume.yaml

apiVersion: v1
kind: Pod
metadata:
  name: app-downward
  labels:
    zone: app-downward
spec:
  containers:
  - name: ct-nginx
    image: nginx
    ports:
      - containerPort: 80
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: POD_NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP