apiVersion: v1
kind: Pod
metadata:
  name: node-affinity1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd            
  containers:
  - name: ct-nginx
    image: nginx
    imagePullPolicy: IfNotPresent