apiVersion: v1
kind: Pod
metadata:
  name: node-affinity3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd
            - ssd
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: hw
            operator: In
            values:
            - gpu
  containers:
  - name: ct-nginx  
    image: nginx