apiVersion: v1
kind: Pod
metadata:
  name: app-config
spec:
  containers:
  - name: ct-nginx
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: config-version