apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: app-readiness
spec:
  containers:
  - name: app-readiness
    image: nginx
    readinessProbe:
      httpGet:
        path: /health.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
