apiVersion: v1
kind: Pod
metadata:
  name: app-secret
spec:
  containers:
  - name: ct-nginx
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: config-secret