apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration1
spec:
  containers:
  - name: ct-nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "ready"
    operator: "Exists"
    effect: "NoSchedule"