apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
  - name: ct-nginx
    image: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 250m