apiVersion: v1
kind: Pod
metadata:
  name: app-sidecar
spec:
  containers:
  - name: ct-busybox
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
  - name: ct-nginx
    image: nginx
    ports:
      - containerPort: 80
